name: Deploy Flask to Cloud Run

on:
  push:
    paths:
      - "Machine_Learning/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Authenticate Docker with GCP
        run: gcloud auth configure-docker

      - name: Check GCP Authentication
        run: gcloud auth list

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-backend"
          cd Machine_Learning
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-backend \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-backend \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars GCLOUD_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},PORT=8080