# name: Deploy Flask to Cloud Run

# on:
#   push:
#     paths:
#       - "Machine_Learning/**"
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: "read"
#       id-token: "write"

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Google Auth
#         uses: "google-github-actions/auth@v1"
#         with:
#           credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

#       - name: Set up Cloud SDK
#         uses: "google-github-actions/setup-gcloud@v1"
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           export_default_credentials: true

#       - name: Configure Docker to Use Google Artifact Registry
#         run: gcloud auth configure-docker asia-southeast2-docker.pkg.d

#       - name: Build and Push Docker Image
#         run: |
#           IMAGE_NAME="asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/flask-backend"
#           cd Machine_Learning
#           docker build -t $IMAGE_NAME .
#           docker push $IMAGE_NAME

#       - name: Deploy to Cloud Run
#         run: |
#           gcloud run deploy flask-backend \
#             --image=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/flask-backend \
#             --region=${{ secrets.GCP_REGION }} \
#             --platform=managed \
#             --allow-unauthenticated \
#             --set-env-vars "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
#             --timeout=300s